### ISSUE TITLE
panic in fromChannel in connection.go

### ISSUE THREAD

**Issue by songgao** [playwright-community/playwright-go#286] opened 2022-07-31 01:45 UTC
Hi, I have a long running process using this and ran into a panic after a while. Is this a known issue?

```
panic: interface conversion: interface {} is nil, not *playwright.channel

goroutine 1 [running]:
github.com/playwright-community/playwright-go.fromChannel(...)
        /Users/songgao/go/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/connection.go:201
github.com/playwright-community/playwright-go.(*pageImpl).Reload(0xc0000e4a00?, {0x0?, 0x0?, 0xc0000a41e0?})
        /Users/songgao/go/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/page.go:188 +0xd6
```

Unfortunately I don't have an easy repro. My setup involves creating a few pages in a chrome browser type and calling `page.Reload()` on each page periodically.

**Comment by canstand** [comment] 2023-09-12 16:27
Pleas try the latest version

**Comment by lampnick** [comment] 2023-12-22 08:48
same issue when I call page.Reload() periodic, using:	github.com/playwright-community/playwright-go v0.4001.0

**Comment by lampnick** [comment] 2023-12-22 08:49
> same issue when I call page.Reload() periodic, using: github.com/playwright-community/playwright-go v0.4001.0

```
panic: interface conversion: interface {} is map[string]interface {}, not *playwright.channel

goroutine 136 [running]:
github.com/playwright-community/playwright-go.fromChannel({0x20551a0, 0xc0024d4d80})
	xxxxx/github.com/playwright-community/playwright-go@v0.4001.0/connection.go:348 +0x66
github.com/playwright-community/playwright-go.fromNullableChannel({0x20551a0, 0xc0024d4d80})
	xxxxx/github.com/playwright-community/playwright-go@v0.4001.0/connection.go:355 +0x3d
github.com/playwright-community/playwright-go.newFrame(0xc0002c6280, {0xc001806294, 0x5}, {0xc001899260, 0x26}, 0xc0024d4d20)
	xxxxx/github.com/playwright-community/playwright-go@v0.4001.0/frame.go:38 +0x4a5
github.com/playwright-community/playwright-go.createObjectFactory(0xc0002c6280, {0xc001806294, 0x5}, {0xc001899260, 0x26}, 0xc0024d4d20)
	xxxxx/github.com/playwright-community/playwright-go@v0.4001.0/objectFactory.go:34 +0x20f
github.com/playwright-community/playwright-go.(*connection).createRemoteObject(0xc0006200c0, 0xc0002c6280, {0xc001806294, 0x5}, {0xc001899260, 0x26}, {0x20551a0, 0xc0024d4d20})
	xxxxx/github.com/playwright-community/playwright-go@v0.4001.0/connection.go:155 +0xbf
github.com/playwright-community/playwright-go.(*connection).Dispatch(0xc0006200c0, 0xc001303ea0)
	xxxxx/github.com/playwright-community/playwright-go@v0.4001.0/connection.go:117 +0x6ce
github.com/playwright-community/playwright-go.(*connection).Start.func1()
	xxxxx/github.com/playwright-community/playwright-go@v0.4001.0/connection.go:54 +0x145
created by github.com/playwright-community/playwright-go.(*connection).Start
	xxxxx/github.com/playwright-community/playwright-go@v0.4001.0/connection.go:46 +0x85
```

**Comment by canstand** [comment] 2023-12-22 11:41
@lampnick `interface {} is map[string]interface {}`, unlike the previous issue, I can't reproduce it. Can you provide reproducible code?

**Comment by dreams-money** [comment] 2024-01-09 01:30
> > @lampnick `interface {} is map[string]interface {}`, unlike the previous issue, I can't reproduce it. Can you provide reproducible code?
> 
> call the page.Reload() every 5 seconds. It maybe reproduce in 1 hour.

Definitely occurs after extended use

**Comment by canstand** [comment] 2024-01-09 13:11
I have tested and confirmed that it‘s an upstream error, see issue https://github.com/microsoft/playwright/issues/28915

**Comment by canstand** [comment] 2024-03-13 05:32
Fixed in latest version.

**Closed by canstand** 2024-03-13 05:32 UTC
Labels: upstream
