### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Chimerax2** [playwright-community/playwright-go#279] opened 2022-06-14 08:33 UTC
Since this morning i've tried the last 3 releases, but they all seem to fail on driver download.

I receive the following error:
```
2022/06/14 08:28:41 Downloading driver to /home/cage/.cache/ms-playwright-go/1.20.0-beta-1647057403000
2022/06/14 08:28:56 could not install playwright: could not install driver: could not install driver: could not download driver: Get "https://playwright.azureedge.net/builds/driver/next/playwright-1.20.0-beta-1647057403000-linux.zip": stream error: stream ID 1; CANCEL
```

Updated to latest version, but still getting the same error.
Happens to anybody else or it is just me ?

**Comment by Chimerax2** [comment] 2022-06-14 08:57
Sometimes it passes that step but still fails with the following:
```
2022/06/14 08:53:17 Downloading driver to /home/cage/.cache/ms-playwright-go/1.20.0-beta-1647057403000
2022/06/14 08:54:08 Downloaded driver successfully
2022/06/14 08:54:08 Downloading browsers...
Failed to install browsers
Error: Failed to download chromium v978106, caused by
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
2022/06/14 08:56:47 could not install playwright: could not install driver: could not install browsers: could not install browsers: exit status 1
```

**Comment by mxschmitt** [comment] 2022-06-14 09:55
Seems like the same as https://github.com/microsoft/playwright/issues/14853

**Comment by ninadingole** [comment] 2022-09-04 07:27
@Chimerax2 could you please recheck if this issue still exists? Thank you 😄

**Comment by mxschmitt** [comment] 2022-09-04 07:41
Closing since this was caused by a temporary Azure outage.

**Closed by mxschmitt** 2022-09-04 07:41 UTC
